Feature/7 kt 11 implement chat functionality
kuna-mata/kuna-talk-backend pull request #9
Opened 2024-11-03 12:16 UTC by ha-ccoon

2024-11-04 02:00 UTC, ImaCodingClown commented on src/chat/chat.service.ts
> +      .findOne({
Find one?

2024-11-05 13:37 UTC, ImaCodingClown requested changes

2024-11-05 13:37 UTC, ImaCodingClown commented on src/chat/chat.service.ts
> +      .findOne({
여기!!!!!

2024-11-07 12:59 UTC, ha-ccoon commented on src/chat/chat.service.ts
> +      .findOne({
다음 브랜치에서 수정하겠씀니당

2024-11-07 13:44 UTC, ha-ccoon commented on src/chat/chat.service.ts
> +      .findOne({
findAll 추가했씁니다

2024-11-07 13:47 UTC, ImaCodingClown approved these changes

2024-11-07 13:55 UTC, ImaCodingClown approved these changes

2024-11-07 13:55 UTC, merged